PHP基礎課題for文、簡単なアプリを作成しよう
tutiyaren/php-base pull request #2
Opened 2024-03-07 22:15 UTC by tutiyaren

PHP基礎課題for文、簡単なアプリを作成しよう

標準入力のため、コードのスクショを貼付します
![スクリーンショット (100)](https://github.com/tutiyaren/php-base/assets/126432220/303bead3-3ffd-4483-ae6b-ac3c7a40a444)

2024-03-08 03:03 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-03-08 03:03 UTC, KatsuyaTanaka95 commented on src/public/app-for-php.php
> +}
教材の解説を参考にガード節で書いてみましょう！！
現場ではガード節で書くことになるので、、慣れておきましょう！！

2024-03-08 12:45 UTC, tutiyaren commented
app-for-php.phpをガード節を使用した記述に修正いたしましたので、ご確認お願いします！

2024-03-10 22:04 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-03-10 22:45 UTC, merged